version: "3.9"
services:
  db:
    image: mariadb:10.6.5-focal
    restart: always
    environment:
      MYSQL_DATABASE: 'BCraft'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'super_duper_user'
  api:
    build: .
    ports:
      - "8000:8000"
    restart: always
    command: "bash ApiRuner"
    depends_on:
      - db