# Generated by Django 3.2.9 on 2021-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('Views', models.IntegerField(verbose_name='Количество показов')),
                ('Clicks', models.IntegerField(verbose_name='Количество кликов')),
                ('Cost', models.FloatField(verbose_name='Стоимость кликов')),
            ],
        ),
    ]
